micronaut:
  application:
    name: mn4-cli-exemplar
  http:
    services:
      worldtimeapi:
        url: "https://worldtimeapi.org/api"
        client-configuration:
          http-version: HTTP_2
          read-timeout: 10s
    client:
      default-client:
        type: jdk
      read-timeout: 5s
      connection-timeout: 5s
